version: '3.9'

services:
  app:
    build: .
    command: python main.py
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: langgraph
      POSTGRES_PASSWORD: langgraph
      POSTGRES_DB: langgraph
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  db_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
